### ISSUE TITLE
Email not going to inbox

### ISSUE THREAD

**Issue by varshini712** [NYU-Molecular-Pathology/snsxt#22]
The run email is not going to the user who actually runs it.

**Comment by stevekm** [comment]
Can you give this new revision a try? Do a `git checkout` on the `origin/default-email` branch, and test it on the server;

```bash
$ snsxt/run.py -d ../example_runs/mini_analysis-controls -a mini_analysis -r results1 -t task_lists/demo-start.yml --debug -f ../example_runs/mini_analysis-controls/fastq/
```

**Comment by stevekm** [comment]
added to the `master` branch, let me know if the problem persists
